version: "3.9"
services:
  db:
    image: postgres:14.1
    command: ["postgres", "-c", "fsync=off", "-c", "synchronous_commit=off", "-c", "full_page_writes=off"]
    environment:
      POSTGRES_PASSWORD: password
  app:
    build: .
    command: bash -c 'cd /code/benchmarking && cargo run --frozen'
    volumes:
      - .:/code
    depends_on:
      - db
